### ISSUE TITLE
On Scene change

### ISSUE THREAD

**Issue by TrayserCassa** [Zylann/godot_debug_draw#3]
Hi,

Maybe I am a bit stupid, but when I change the scene and want to print data it doesn't get shown.
In my `Login.tscn` I see the debug output, then I switch the scene and want to print player data. I invalidate the `_canvas_item` and set it to `null` but it doesn't show up, but the path is now correct. 
Should this work? When yes, then I will debug more into this.

**Comment by Zylann** [comment]
I don't understand well what your setup is. The DebugDraw node is best used as an autoload, so changing scene would not affect it. If you added it in a scene instead, if you change scene it's going to be removed with the nodes of the previous scene.

**Comment by TrayserCassa** [comment]
Ah yes your right, but I was using it in my gui node, because I needed it with the camera. And I switched the node offen this might be not the right way it to do, but there I have every property which is useful to log. 

I changed the stuff directly in the code and switch the canvas layer out if I'm switching the root node.
